### ISSUE TITLE
Header file is missing

### ISSUE THREAD

**Issue by comsians123** [jtgrassie/xmr-wasm#1]
Hi,
Following header file is missing
[source code link](https://github.com/jtgrassie/xmr-wasm/blob/master/src/crypto/hash.h#L35)
From where I can get this header file?
Thanks

![xmrwasm](https://user-images.githubusercontent.com/23478572/46947636-70e44c00-d049-11e8-8566-c6837ed0d70f.png)

**Comment by jtgrassie** [comment]
Just install boost.
